'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class productosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=productosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property categorias() As DbSet(Of categoria)
    Public Overridable Property colores() As DbSet(Of colore)
    Public Overridable Property productoes() As DbSet(Of producto)
    Public Overridable Property tallas() As DbSet(Of talla)

End Class
