'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property id_producto As Integer
    Public Property id_categoria As Nullable(Of Integer)
    Public Property precio As Nullable(Of Double)
    Public Property estado As String
    Public Property producto1 As String

    Public Overridable Property categoria As categoria

End Class
